#!/bin/sh
# helper 自己会先 bootout 旧的 LaunchDaemon 再注册新的，覆盖安装无需额外处理
set -e

bin='/Library/Application Support/ECYCloud/bin'

# 换内核前的版本随包分发 sing-box，pkg 只覆盖载荷不清理消失的文件，
# 不点名删就会在用户机上一直留着几十 MB 的旧内核
rm -f "$bin/sing-box" "$bin/LICENSE.sing-box.txt"

"$bin/ecycloud-helper" install
exit 0
